# llm: gpt-4o-mini # NOTE: gpt-4o-mini is faster and cheaper than gpt-4o and can still do structured output very well
# TODO: Get a local model that can do structured output

# llm: vllm_meta-llama/Llama-3.1-8B-Instruct
# tool_call_llm: vllm_tool_call_meta-llama/Llama-3.1-8B-Instruct
# fast_llm: vllm_meta-llama/Llama-3.1-8B-Instruct
# summarize_llm: vllm_meta-llama/Llama-3.1-8B-Instruct

# llm: vllm_mistralai/Mistral-7B-Instruct-v0.3
# tool_call_llm: vllm_tool_call_mistralai/Mistral-7B-Instruct-v0.3
# fast_llm: vllm_mistralai/Mistral-7B-Instruct-v0.3
# summarize_llm: vllm_mistralai/Mistral-7B-Instruct-v0.3

llm: ollama_llama3.1:70b
tool_call_llm: ollama_llama3.1:70b
fast_llm: ollama_llama3.1:70b
summarize_llm: ollama_llama3.1:70b

max_tool_call_retries: 3
max_retries: 3
llm_temperature: 0.0
embedding_model: nomic-embed-text
vector_store_collection_name: fashion_trends
search_plan_retry_limit: 3
num_search_iterations: 5
vector_search_type: mmr
vector_search_k: 5
vector_search_fetch_k: 20
max_clothing_search_retries: 3
max_search_results: 5
max_clothing_items_to_stream: 5
max_images_to_display: 5
min_sources_for_summary: 1
chunk_size: 5000
chunk_overlap: 100
chunk_batch_size: 1
max_queue_size: 100
logging_dir: ../logs
clothing_parser_timeout: 240.0
link_click_timeout: 20.0
should_continue_prompt: |
  Given the user's original question: {original_question}
  and the last message in the conversation: {last_message}

  Is the agent's task complete? Answer with a boolean should_continue=False if the task is done, 
  or should_continue=True if more actions or information are needed.

  Example 1:
  original_question: "What is the capital of the France?"
  last_message: "The capital of France is Paris."
  should_continue: False

  Example 2:
  original_question: "What is the capital of the France?"
  last_message: "I don't know the capital of France."
  should_continue: True
select_action_plan_prompt: |
  You are a helpful assistant tasked with selecting the right tool to answer a user's question.
  You must choose a tool to answer the user's question rather than providing a response yourself.
  You have access to the following tools:

  Tools:

  {subgraph_descriptions}

  Remember to respond with the name of the tool you want to call and nothing else.

  Select the tool that best fits the user's question.
  User Question:
  {user_question}
summarize_docs_prompt: |
  Summarize the following documents in relation to the user's question.
  Make sure to include the following sources of the information used to create the summary.
  Include the markdown-formatted images used to create the summary in your response.
  Remember to include images using their URLs with the markdown image syntax: ![alt text](image_url)

  User Question:
  {question}

  Source Documents:
  {docs}

  Sources Links:
  {sources}

  Image URLs:
  {image_links}

  Please provide a concise and informative summary that directly addresses the question.
  Provide the sources at the bottom in a separate sources section.

  SUMMARY WITH SOURCES AND IMAGES:
summarize_docs_prompt_no_images: |
  Summarize the following documents in relation to the user's question.
  Make sure to include the following sources of the information used to create the summary.

  User Question:
  {question}

  Sources:
  {sources}

  Documents:
  {docs}

  Please provide a concise and informative summary that directly addresses the question.
  Provide the sources at the bottom in a separate sources section.

  SUMMARY WITH SOURCES:
summarize_weekly_prompt: |
  You are an expert fashion blogger writing an article to describe the last week's fashion trends.
  It is currently {current_month} {current_day}, {current_year}.

  Create a balanced summary of men's and women's fashion trends for all clothing types.
question_filter_prompt: |
  You are a helpful assistant. Your job is to filter user questions to make sure the user is asking about clothing.
  If the user is asking about clothing, return "True". If the user is not asking about clothing, return "False".

  User Question:
  {user_question}

  Make sure to only return "True" or "False" and nothing else.

  ANSWER:
clothing_extractor_prompt: |
  You are an expert fashion blogger and stylist.
  Your goal is to rephrase your client's search query into an optimal web search for clothing to match their request.

  User Question:
  {user_question}

  Search Query:
clothing_search_result_parser_prompt: |
  You are an expert fashion blogger and stylist and software engineer.
  Your goal is to parse the content of a web page to extract information about the clothing items displayed on the page.
  Return only the parsed clothing item and nothing else.
  When constructing the clothing item, make sure to use the URL of the page as the source of the clothing item.
  Make sure the image URL you include is accessible from a web browser independently of the current page's context.

  Web Page URL:
  {url}

  Web Page Content:
  {content}

  Parsed Clothing Item:
html_contains_clothing_info_prompt: |
  Given the following HTML snippet, determine if it contains information about a clothing item or links that are promising for finding clothing items.
  Return "true" if it does, "false" otherwise.

  HTML:
  {html}

  Answer:
is_clothing_product_link_prompt: |
  Given the following URL:
  {url}

  Is this a URL for a clothing product?
  Return "true" if it is, "false" otherwise.
