repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true