llm: llama3.1
llm_temperature: 0.0
embedding_model: nomic-embed-text
vector_store_collection_name: fashion_trends
search_plan_retry_limit: 3
num_search_iterations: 5
vector_search_type: mmr
vector_search_k: 10
vector_search_fetch_k: 5
logging_dir: logs